from enum import Enum, auto


class Specialisation(Enum):
    Balance = auto()
    Feral = auto()
    Restoration = auto()
    BeastMastery = auto()
    Marksmanship = auto()
    Survival = auto()
    Arcane = auto()
    Fire = auto()
    Frost = auto()
    Holy = auto()
    Protection = auto()
    Retribution = auto()
    Discipline = auto()
    Holy = auto()
    Shadow = auto()
    Assassination = auto()
    Combat = auto()
    Subtlety = auto()
    Elemental = auto()
    Enhancement = auto()
    Restoration = auto()
    Affliction = auto()
    Demonology = auto()
    Destruction = auto()
    Arms = auto()
    Fury = auto()
    Protection = auto()
    BloodFrost = auto()
    Unholy = auto()
    Brewmaster = auto()
    Mistweaver = auto()
    Windwalker = auto()
    Havoc = auto()
    Vengeance = auto()
